### ISSUE TITLE
Immediate Issues

### ISSUE THREAD

**Issue by Trigition** [nmtminecraft/Regicide#1]
-Being killed outside game means player is not spawned at lobby. (Fixed, needs testing.)
    -Getting killed after 'entering' game but before 'starting' causes players to prematurely
     enter game zones. (Fixed needs testing)
-Players can break itemframes/get items
-No players got teleported to Others Location (Fixed, needs testing.)
-Getting killed by mob causes misplaced spawn (Fixed needs testing.)
-Frame Lag for firework particles (fireworks removed)
-Always set Day

-Clicking too fast causes internal server errors. FIX THIS.

**Comment by smarti02** [comment]
Fixed the "-Being killed outside game means player is not spawned at lobby." needs to be tested

**Comment by smarti02** [comment]
as a side note players cannot pick up the items they dislodge from the item frames so that might not be a problem.

**Comment by Trigition** [comment]
I think I fixed players not teleporting to the 'others' location when the game ends.
