### ISSUE TITLE
Non-Critical Issues

### ISSUE THREAD

**Issue by Trigition** [nmtminecraft/Regicide#2]
-Players can kill each other outside of game (do we want this?)
-scoreboards aren't popping up right away
-steak in air
-Less Villagers/More Spawn Locations/Bigger Map
-Name Flash
-No cohesion for players (Find incentive to work together?)

**Comment by smarti02** [comment]
What is the steak in air error?

**Comment by Trigition** [comment]
I forgot I just copied this straight over.

The King can't eat when facing a player or a block in close proximity (Skyler says this is probably due to World Guard acting up).

**Comment by smarti02** [comment]
ah ok
